name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize and update specific submodule
      run: |
        git submodule init https://github.com/LarissaTerto/website-vuejs
        git submodule update https://github.com/LarissaTerto/website-vuejs
        
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install NVM
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install 14
        nvm use 14

    - name: Install dependencies
      run: npm install

    - name: Install additional packages
      run: npm install leaflet vue2-leaflet

    - name: Run the project
      run: npm run serve
